### PR TITLE
Add Battle Simulation

### PR DESCRIPTION
**Pull request by the-marenga**
- Add a generic battle framework 
- Working player, monster and companion fighter conversion
- Damage and overall effect calculations should be somewhat correct
- Add the stats of a bunch of dungeon enemies as constants
- Add a logging mechanismus to serialize, or log the result of battle simulations
- Fix pet parsing bug
- Fix gem bugs 

There is still some stuff missing (All Necromancer minion effects) and some parts are likely going to be wrong (dodging), but I can never be certain that this will be correct, so I will likely merge this is a working, but still flawed state

### CODE REVIEW

**Comment by GutZuFusss** [comment]
Impressive

**Comment by Seraphine725** [comment]
here are the stats for the training camp, have no account that has the new sandstorm unlocked so can not help there

| name         | floor | class   | level | health | xp   | strength | dexterity | intelligence | constitution | luck |
|--------------|-------|---------|-------|--------|------|----------|-----------|--------------|--------------|------|
| TrainingCamp |     0 | Mage    |     1 |     50 |   80 |        5 |         5 |           10 |           10 |    5 |
| TrainingCamp |     1 | Mage    |     2 |    120 |  180 |       10 |        10 |           20 |           20 |   10 |
| TrainingCamp |     2 | Scout   |     3 |    480 |  280 |       15 |        30 |           15 |           30 |   15 |
| TrainingCamp |     3 | Warrior |     4 |   1000 |  360 |       40 |        20 |           20 |           40 |   20 |
| TrainingCamp |     4 | Warrior |     5 |   1500 |  440 |       50 |        25 |           25 |           50 |   25 |
| TrainingCamp |     5 | Mage    |     6 |    840 |  578 |       30 |        30 |           60 |           60 |   30 |
| TrainingCamp |     6 | Scout   |     7 |   2240 |  716 |       35 |        70 |           35 |           70 |   35 |
| TrainingCamp |     7 | Warrior |     8 |   3600 |  881 |       80 |        40 |           40 |           80 |   40 |
| TrainingCamp |     8 | Scout   |     9 |   3600 | 1071 |       40 |        80 |           40 |           90 |   45 |
| TrainingCamp |     9 | Mage    |    10 |   2200 | 1287 |       40 |        40 |           80 |          100 |   50 |

**Comment by GutZuFusss** [comment]
I can help with all Dungeons except sandstorm.

**Comment by the-marenga** [comment]
Are you refering to [this](https://forum.ragezone.com/threads/dl-tutorial-shakes-fidget-remastered-working-server-files-2024.1228302/) or [this](https://github.com/HafisCZ/sf-tools)? I know they have a bunch of stuff figured out already, but I want to keep away from  copy-pasting code from other people. Especially damage calcs are often different/wrong between sf-tools/mfbot/private-servers and I don't want to get into "you stole my code" arguments later down the line, since none of them have any open source license.

If you have any good resource I am not aware of, feel free to share them

**Comment by GutZuFusss** [comment]
> Are you refering to [this](https://forum.ragezone.com/threads/dl-tutorial-shakes-fidget-remastered-working-server-files-2024.1228302/) or [this](https://github.com/HafisCZ/sf-tools)? I know they have a bunch of stuff figured out already, but I want to keep away from copy-pasting code from other people. Especially damage calcs are often different/wrong between sf-tools/mfbot/private-servers and I don't want to get into "you stole my code" arguments later down the line, since none of them have any open source license.
> 
> If you have any good resource I am not aware of, feel free to share them

Can you please remove that comment? What you call "p server" is actually leaked playa code, so yea... The order of applying bonuses should be just about right ;) Not sure why one would consider that "stealing code", it is looking at the ground truth for an aspect, that would otherwise take unreasonable amounts of data collection and analysis. I am not talking about taking anything. There are just some aspects, that are not really observable without having a peek inside the black box.

That is by the way something I now know for a fact SFTools messed up, not sure if it was always broken or the discrepancy was introduced by an update on playas side.

On a side note I SFTools has a green light on embedding their compiled client. From what I can tell it's only used for authentication and data fetching though, not sure what the reason is he did't use more of the "real deal"-code, but again... I quickly loose patience when reading SFTools code.

**Pull request merged**
