### PR TITLE
fix stlye issues and required points for the final chest

### PR DESCRIPTION
**Pull request by Seraphine725**
As discussed in #93

### CODE REVIEW

**Comment by the-marenga** [comment]
Thanks for the follow-up. Pretty sure `POINTS_REQUIRED_FOR_CHEST`can  also be removed now, right?

I also just checked something. There was an unused int in the parsing for the rewards chest, that was always just equivalent to the index, so I ignored it. 
https://github.com/the-marenga/sf-api/blob/e3a6a3b23eb994a786a10d8e25d7d357bf2e66a4/src/gamestate/rewards.rs#L720
It seems like in one their updates, they actually did a senseable thing and changed the int to now contain the amount of points needed. That means the required points for all chest can be anything, not just 5/10/13/20. 

grafik

If you want, you can have a look at the parsing of that, otherwise I would just merge this and implement that, when I get around to it?

**Comment by Seraphine725** [comment]
yeah sure I'll take a look

**Comment by Seraphine725** [comment]
tested it a bit and it should work

**Comment by the-marenga** [comment]
Thank you very much!

**Pull request merged**
